# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fffcd6cfbfc1344d463d173cfd871d1db94f7d8df0ae93585bbd48a33ca37ed16ad69a30e260a7d269a774c8d7661af2e08fc0d7ab98165f25e162f7a0942c65

test:
  secret_key_base: 0e5b17d54c7987d425c0005b78f720cfbf95eab2ab9792b55c163b533e148d8f5067db2ef22019a8897eefc481643bc7ee49b60429df451dc9d61dc2bfa8c699

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
